### ISSUE TITLE
Commands dir, file list: fail well when not inside a package

### ISSUE THREAD

**Issue by sckott** [sckott/rt-cli#5]
Right now we do give useful info but could print a simpler (e.g., one liner) message

```
# not in a R pkg
rt dir .
```

```
Error in `package_file()`:
! Could not find package root.
ℹ Is . inside a package?
Backtrace:
    ▆
 1. └─devtools::test(".")
 2.   └─devtools::as.package(pkg)
 3.     └─devtools::package_file(path = x)
 4.       └─cli::cli_abort(c("Could not find package root.", i = "Is {.path {base_path}} inside a package?"))
 5.         └─rlang::abort(...)
Execution halted
The rt subprocess exited with an error: ExitStatus(unix_wait_status(256))
```

`rt list` just doesn't return anything - which maybe is fine but ideally these 3 commands behave the same

**Comment by sckott** [comment]
Partially done

- [x] `list` via #6 
- [ ] `dir`
- [ ] `file`

**Comment by JosiahParry** [comment]
I was playing with this a bit. I tried capturing stderr so that this didn't happen. However, `stderr` is used by cli so removing that ruins the output for successful runs. 

I think the solution is to do the checks that are done by devtools / testthat manually. 

For `dir` we could check if the `{path}/DESCRIPTION` exists. If not we fail with our own error message via `eprintln!()`. 

For example 
```
let pkg_exists = std::fs::exists(&format!("{}/DESCRIPTION", &cmd.dir));

if pkg_exists.is_err() {
  eprintln!()
  return ();
}
```

Do you want to take this on?

**Comment by sckott** [comment]
Ah ok, thanks for checking on that!

Yeah, I'll give it a shot

**Comment by JosiahParry** [comment]
Give me an @ if you get stuck :)

**Comment by sckott** [comment]
@JosiahParry A bit stuck here. The `.is_err()` route didn't work, so I've been trying https://doc.rust-lang.org/std/path/struct.Path.html#method.exists which works for the `dir` subcommand, but stuck on the `file` subcommand. 

```rust
let file = format!("{}", &cmd.file);
let mut ancestors = Path::new(&file).ancestors();

// But then when I go through the iterator I can get to the right one, but I'm not sure how to get there more succinctly
// Maybe there's some sort of map function to use here?
// Running `rt file tests/testthat/test-client-verb.R` in a dir for an R package locally:
ancestors.next(); 
// gives self: Some("tests/testthat/test-client-verb.R")
ancestors.next(); 
// gives one parent up: Some("tests/testthat")
ancestors.next(); 
// gives tests dir: Some("tests")
ancestors.next(); 
// Then gives an empty str: Some(""), this one does work if I use this path e.g. `&x.unwrap().join("DESCRIPTION")` 
```

**Comment by JosiahParry** [comment]
@sckott do you a have a branch that you're working on that I can look at?

**Comment by sckott** [comment]
yeah I'll push

**Comment by JosiahParry** [comment]
Awesome! Lmk when you complete that

**Comment by sckott** [comment]
Okay, opened a PR and pinged you there
